### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by stormkingz** [shelhamer/clockwork-fcn#1]
I have tried the "pascal-translate-exp.ipynb", and find some typos,
1) in shell [2], "caffe.set_device(1)", I think it's better to use "caffe.set_device(0)".
2) in shell [5], '../nets/fcn-pool3-pascal.caffemodel', '../nets/fcn-pool4-pascal.caffemodel', but in your "clockwork-nets" package, the corresponding file is  "voc-fcn-pool3.caffemodel" and "voc-fcn-pool4.caffemodel". I think it's better to use the same names.

**Comment by shelhamer** [comment]
Thanks for catching these; fixed.
