### ISSUE TITLE
CamVid dataset  code for clockwork-fcn

### ISSUE THREAD

**Issue by yacineDZ44** [shelhamer/clockwork-fcn#10]
Hi, shelhamer. I have test your code and it works fine with cityscapes.
I'm using CamVid dataset and i want to use your network on this dataset.
Could you provide caffemodel for this dataset?
Thank you.

**Comment by SiyingLiang** [comment]
Did you test successfully on cityscapes dataset?  Have you found the module called labels?

**Comment by yacineDZ44** [comment]
Hi,
Yes I tested it successfully on cityscapes dataset. The labels module is
available at cityscapes github repository, you can download it and place it
at the right location.
cordially.

Le dim. 19 mai 2019 à 11:50, SiyingLiang <notifications@github.com> a
écrit :

**Comment by shelhamer** [comment]
> I'm using CamVid dataset and i want to use your network on this dataset.

We do not have CamVid experiments or pre-trained models, but hopefully the code and notebooks for PASCAL VOC and Cityscapes can be a guide to incorporating the CamVid dataset.

Good luck with your work!

**Comment by yacineDZ44** [comment]
Thank you @shelhamer .
