### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by wolf943134497** [shelhamer/clockwork-fcn#2]
Hi @shelhamer  

How to use and test this code ?can you give me a guidance? Thanks

**Comment by shelhamer** [comment]
The notebooks linked from the README, such as this notebook on [cityscapes clockwork](http://nbviewer.jupyter.org/github/shelhamer/clockwork-fcn/blob/master/notebooks/cityscapes-clockwork-exp.ipynb), indicate the usage of the code. The notebooks altogether cover the experiments in the arxiv.
