### ISSUE TITLE
nets/cityscapes-fcn8s.prototxt is lost

### ISSUE THREAD

**Issue by mingminzhen** [shelhamer/clockwork-fcn#3]
nets/cityscapes-fcn8s.prototxt is lost

**Comment by tonysy** [comment]
'../nets/stage-cityscapes-fcn8s.prototxt' @shelhamer there is no prototxt in your repo, it would be greate if you can provide this file, thanks.

**Comment by tonysy** [comment]
Sorry for this stupid question, the prototxt will be created when exec the scripts in ./nets/. Thanks a lot

**Comment by shelhamer** [comment]
no problem! ☕️
