### ISSUE TITLE
how to train clockwork-fcn

### ISSUE THREAD

**Issue by tonysy** [shelhamer/clockwork-fcn#4]
Hi, shelhamer. I have test your code and it works fine.
While I haven't find the scripts or steps about how to train this clockwork-fcn network. Would you give me a hand? 
Thanks a lot.

**Comment by shelhamer** [comment]
To clarify, the nets in this project are all trained as regular, single-frame FCNs according to [fcn.berkeleyvision.org](http://fcn.berkeleyvision.org)

**Comment by wujiyoung** [comment]
@shelhamer I have some problems when training in [fcn.berkeleyvision.org](https://github.com/shelhamer/fcn.berkeleyvision.org), and I want to report to you by opening some issues. However, it seems that  you closed the issue module?
