### ISSUE TITLE
Can you tell me how to infer a new movie with the pascal caffe model ?

### ISSUE THREAD

**Issue by daicoolb** [shelhamer/clockwork-fcn#5]
I want to  use it to infer a new movie . how to do it ?

**Comment by shelhamer** [comment]
The notebooks show how to run alternating and adaptive clockwork inference https://github.com/shelhamer/clockwork-fcn/blob/master/notebooks/youtube-clockwork-exp.ipynb as well as pipelined inference https://github.com/shelhamer/clockwork-fcn/blob/master/notebooks/youtube-pipeline-exp.ipynb

The inference code is somewhat tied up in the dataset code (sorry!), but if you refer to the "Adaptive Clockwork" cell you can see that it's mostly a matter of

1. loading all of the video frames
2. running the net partially by `run_net.feed_net()` on every frame
3. checking the clock by `sm_diff()`
4. running the rest of the net or not according to the clock
5. merging the layers scores for the new output

Note that the youtube results are making use of our pre-trained PASCAL FCN—we did not train on youtube at all.

Hope that helps!

**Comment by daicoolb** [comment]
Thanks a Lot . I will try it
