### ISSUE TITLE
where can I find all the .prototxt files ?

### ISSUE THREAD

**Issue by citlag** [shelhamer/clockwork-fcn#7]
First for the installation it says to install everything in "requirements.txt" but file is missing.

Also, I am trying to test your code but I need the "prostage-cityscapes-fcn8s.prototxt". In general if I want to test all the prototxt are missing, can you provide them?

Thanks

**Comment by shelhamer** [comment]
The nets are defined by python net spec in https://github.com/shelhamer/clockwork-fcn/tree/master/nets and the prototxt are generated by running the scripts by `python net-fcn8s.py` for example. See #3.
