### ISSUE TITLE
train.prototxt and solver.prototxt

### ISSUE THREAD

**Issue by EternityZY** [shelhamer/clockwork-fcn#9]
Hi, thank you for sharing this great work.
I want to training this network,but I facing some problem about training detail. If you release the train.prototxt and solver.prototxt, I will be very grateful to you.
Thank you !

**Comment by shelhamer** [comment]
All of the nets are the pre-trained nets from [fcn.berkeleyvision.org](https://fcn.berkeleyvision.org) and the training details can be found there. Our clockwork inference method does not require further training.
